# Generated by Django 4.1.7 on 2023-02-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_delete_loginpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Info',
            fields=[
                ('Student_Name', models.CharField(max_length=30)),
                ('Class', models.IntegerField()),
                ('RollNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('DateOfBirth', models.DateField(max_length=30)),
                ('Gender', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Perfomance',
            fields=[
                ('Student_Name', models.CharField(max_length=30)),
                ('Class', models.IntegerField()),
                ('RollNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('Grade', models.CharField(max_length=10)),
                ('Remarks', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Info',
            fields=[
                ('Name', models.CharField(max_length=30)),
                ('TeacherId', models.IntegerField(primary_key=True, serialize=False)),
                ('Mobile_Number', models.IntegerField(max_length=10)),
                ('Qualification', models.CharField(max_length=30)),
                ('DateOfJoining', models.DateField(max_length=30)),
                ('Gender', models.CharField(max_length=10)),
                ('Subject', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Perfomance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_Name', models.CharField(max_length=30)),
                ('TeacherId', models.IntegerField()),
                ('Subject', models.CharField(max_length=30)),
                ('Remarks', models.CharField(max_length=20)),
            ],
        ),
    ]
