# Generated by Django 4.1.7 on 2023-02-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Info',
            new_name='Student_Data',
        ),
        migrations.RenameModel(
            old_name='Teacher_Info',
            new_name='Teacher_Data',
        ),
    ]
