# Generated by Django 4.1.7 on 2023-02-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_student_info_student_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_data',
            name='Mobile_Number',
            field=models.IntegerField(),
        ),
    ]
