# Generated by Django 4.1.7 on 2023-02-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_teacher_data_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='DateOfBirth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='teacher_data',
            name='DateOfJoining',
            field=models.DateField(),
        ),
    ]
