# Generated by Django 4.1.7 on 2023-02-28 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_student_data_dateofbirth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_data',
            name='Mobile_Number',
        ),
    ]
