# Generated by Django 4.1.7 on 2023-02-28 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_remove_teacher_data_mobile_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Perfomance',
            new_name='Student_Performance',
        ),
        migrations.RenameModel(
            old_name='Teacher_Perfomance',
            new_name='Teacher_Performance',
        ),
    ]
